logging:
  level:
    com.recipia.member: info
    org.springframework.web.servlet: info
    org.hibernate.orm.jdbc.bind: info
    org.springframework.cloud.sleuth: info

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${REGION}
      sns:
        topics:
          nickname-change: arn:aws:sns:${REGION}:${ACCOUNT_ID}:NicknameChange
          signUp: arn:aws:sns:${REGION}:${ACCOUNT_ID}:signUp
      sqs:
        record-sqs-name: member-event-record-sqs
      s3:
        bucketName: recipia-file