logging:
  level:
    com.recipia.member: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${MEMBER_DB_URL}
    username: ${DB_MASTER_USERNAME}
    password: ${DB_MASTER_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  application:
    name: member

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${REGION}
      sns:
        topics:
          nickname-change: arn:aws:sns:${REGION}:${ACCOUNT_ID}:sns-test
#          topic1: arn:aws:sns:${REGION}:${ACCOUNT_ID}:topic1
      sqs:
        nickname-sqs-name: sqs-test


server:
  port: 8081
