logging:
  level:
    com.recipia.member: info
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.cloud.sleuth: info

  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${MEMBER_DB_URL}
    username: ${DB_MASTER_USERNAME}
    password: ${DB_MASTER_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  application:
    name: member

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${REGION}
      sns:
        topics:
          nickname-change: arn:aws:sns:${REGION}:${ACCOUNT_ID}:sns-test
      sqs:
        nickname-sqs-name: sqs-test
        record-sqs-name: member-sns-published-record-sqs

  sleuth:
    web:
      servlet:
        skip-pattern: /member/test.*

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://${EC2_PUBLIC_DNS}:9411/api/v2/spans