logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'



spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${MEMBER_DB_URL}
    username: ${DB_MASTER_USERNAME}
    password: ${DB_MASTER_PASSWORD}

  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: true

  jpa:
    database: POSTGRESQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  # kakao OAuth2 정보 추가
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao #springBoot의 기본 방식을 적용
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao" #이렇게하면 알아서 {}안에 domain을 넣어준다. 근데 yml에서는 {}은 제대로 못읽는다.그래서 ""로 감싸주어야 한다.
            client-authentication-method: none #http method도 설정해준다.
        provider:
          kakao: # 공식 페이지에서 정보를 확인해서 넣어주자
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  sleuth:
    http:
      include-patterns=/member/nicknameChange,/feign/member/getNickname
      ignore-patterns=/health

  application:
    name: member

server:
  port: 8081

management:
  metrics:
    web:
      server:
        auto-time-requests: true
  endpoints:
    web:
      exposure:
        include: 'prometheus'  # 이 부분을 수정
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://${EC2_PUBLIC_DNS}:9411/api/v2/spans